# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
defaults: &defaults
  omniauth_openhub:
    google:
      client_id: '506873984206-19ctlcmtb86s7dottvvg8d8p2m4380jv.apps.googleusercontent.com'
      client_secret: 'r4chE5rpJ6tVHKf4bvyplG7z'
    vkontakte:
      client_id: '6622633'
      client_secret: 'H3PenPzIKjrdCEM3RnWy'
    facebook:
      client_id: '199756737401267'
      client_secret: 'edfc06590446c4e9e45d510014d6151d'

development:
  secret_key_base: 24e40d7e924b1e9ff0b376a21464c376fa9925c400c93c07a6790288e32d349ef04a9c716abdb22316649f4c454598f75078823f821c4570ff4f9a44e8e2ded1
  omniauth_openhub:
    google:
      client_id: '506873984206-19ctlcmtb86s7dottvvg8d8p2m4380jv.apps.googleusercontent.com'
      client_secret: 'r4chE5rpJ6tVHKf4bvyplG7z'
    vkontakte:
      client_id: '6622633'
      client_secret: 'H3PenPzIKjrdCEM3RnWy'
    facebook:
      client_id: '199756737401267'
      client_secret: 'edfc06590446c4e9e45d510014d6151d'

test:
  secret_key_base: b1bec2e6e01f7050b61239aed88fd786d7f83e946f8711091da0b12622f1090c41829d54e1ed3eddc1a7217a0793902e6ccc7004c2de79dc3aef78090137a3d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  omniauth_openhub:
    google:
      client_id: '506873984206-19ctlcmtb86s7dottvvg8d8p2m4380jv.apps.googleusercontent.com'
      client_secret: 'r4chE5rpJ6tVHKf4bvyplG7z'
    vkontakte:
      client_id: '6622633'
      client_secret: 'H3PenPzIKjrdCEM3RnWy'
    facebook:
      client_id: '199756737401267'
      client_secret: 'edfc06590446c4e9e45d510014d6151d'
